import type { Field, PageGroup, SectionDef } from "@/lib/cms/types";
import { company } from "@/lib/company";
import { ceoMessage, lab, mining, mission, partner, trading, vision } from "@/lib/content";
import { productCategories, products } from "@/lib/products";
import { services } from "@/lib/services";
import { projects } from "@/lib/projects";
import { team } from "@/lib/team";
import { postCategories, posts } from "@/lib/posts";
import { testimonials } from "@/lib/testimonials";

/**
 * The certificates shipped with the site. They seed the quality section so the
 * gallery keeps working until an admin edits it.
 */
const bundledCertificates = [
  { title: "ISO 9001:2015 — Quality Management", src: "/images/cert-9001.jpg" },
  { title: "ISO 14001:2015 — Environmental", src: "/images/cert-14001.jpg" },
  { title: "ISO 45001:2018 — Health & Safety", src: "/images/cert-45001.jpg" },
  { title: "ISO 630-1:2021 — Structural Steel", src: "/images/cert-630.jpg" },
];

/** Reusable field shapes. */
const ctaFields = (prefix: string, label: string): Field[] => [
  { key: `${prefix}Label`, label: `${label} — label`, type: "text" },
  { key: `${prefix}Href`, label: `${label} — link`, type: "url" },
];

const headingFields: Field[] = [
  {
    key: "eyebrowNumber",
    label: "Eyebrow number",
    type: "text",
    help: "The large orange numeral, e.g. 02. Leave empty to hide it.",
  },
  { key: "eyebrowLabel", label: "Eyebrow label", type: "text" },
];

export const pageGroups: PageGroup[] = [
  {
    key: "global",
    label: "Global",
    path: "/",
    icon: "Globe",
    description: "Brand, company details, navigation, footer and SEO — shared by every page.",
  },
  { key: "home", label: "Home page", path: "/", icon: "Home", description: "Every band on the homepage, top to bottom." },
  {
    key: "about",
    label: "About page",
    path: "/about",
    icon: "Building2",
    description: "Story, values, CEO message, vision, mission, mining and team.",
  },
  {
    key: "products",
    label: "Products",
    path: "/products",
    icon: "Package",
    description: "Products page header and the full product catalogue.",
  },
  {
    key: "services",
    label: "Services",
    path: "/services",
    icon: "Wrench",
    description: "Services page header and the service cards.",
  },
  {
    key: "projects",
    label: "Projects",
    path: "/projects",
    icon: "HardHat",
    description: "Projects page header and the project list.",
  },
  {
    key: "events",
    label: "Events",
    path: "/events",
    icon: "CalendarDays",
    description: "Events page header and empty state. Individual events are managed separately.",
  },
  {
    key: "blog",
    label: "Blog",
    path: "/blog",
    icon: "Newspaper",
    description: "Blog page header and the articles.",
  },
  {
    key: "contact",
    label: "Contact",
    path: "/contact",
    icon: "Mail",
    description: "Contact page header, form copy and the map.",
  },
];

export const sectionDefs: SectionDef[] = [
  /* ─────────────────────────────── GLOBAL ─────────────────────────────── */
  {
    key: "global.brand",
    label: "Brand & navigation",
    page: "global",
    description: "Logo, wordmark, header button and the main menu.",
    previewPath: "/",
    fields: [
      { key: "logo", label: "Logo", type: "image" },
      { key: "wordmarkPrimary", label: "Wordmark — first word", type: "text" },
      { key: "wordmarkAccent", label: "Wordmark — accent word", type: "text" },
      ...ctaFields("headerCta", "Header button"),
      {
        key: "navLinks",
        label: "Menu links",
        type: "list",
        wide: true,
        itemTitleKey: "label",
        addLabel: "Add menu link",
        of: [
          { key: "label", label: "Label", type: "text" },
          { key: "href", label: "Link", type: "url" },
        ],
      },
    ],
    defaults: {
      logo: "/images/logo.png",
      wordmarkPrimary: "Maisam",
      wordmarkAccent: "Steel",
      headerCtaLabel: "Get in touch",
      headerCtaHref: "/contact",
      navLinks: [
        { label: "Home", href: "/" },
        { label: "About", href: "/about" },
        { label: "Products", href: "/products" },
        { label: "Services", href: "/services" },
        { label: "Projects", href: "/projects" },
        { label: "Events", href: "/events" },
        { label: "Blog", href: "/blog" },
        { label: "Contact", href: "/contact" },
      ],
    },
  },
  {
    key: "global.company",
    label: "Company details",
    page: "global",
    description:
      "Name, contact details, headline figures, offices and social links. Used across the whole site.",
    previewPath: "/contact",
    fields: [
      { key: "name", label: "Company name", type: "text" },
      { key: "shortName", label: "Short name", type: "text" },
      { key: "tagline", label: "Tagline", type: "text", wide: true },
      { key: "description", label: "Description", type: "textarea", wide: true },
      { key: "email", label: "Email", type: "text" },
      { key: "emailAlt", label: "Alternate email", type: "text" },
      { key: "phone", label: "Phone", type: "text" },
      { key: "phoneAlt", label: "Alternate phone", type: "text" },
      { key: "address", label: "Address", type: "textarea", wide: true },
      { key: "mapLink", label: "Google Maps link", type: "url", wide: true },
      { key: "mapEmbed", label: "Google Maps embed URL", type: "url", wide: true },
      { key: "founded", label: "Founded", type: "number" },
      { key: "ceo", label: "CEO", type: "text" },
      {
        key: "stats",
        label: "Headline figures",
        type: "list",
        wide: true,
        itemTitleKey: "label",
        addLabel: "Add figure",
        of: [
          { key: "value", label: "Value", type: "number" },
          { key: "suffix", label: "Suffix", type: "text", placeholder: "+" },
          { key: "label", label: "Label", type: "text" },
        ],
      },
      {
        key: "offices",
        label: "Offices & footprint",
        type: "list",
        wide: true,
        itemTitleKey: "city",
        addLabel: "Add office",
        of: [
          { key: "city", label: "City", type: "text" },
          { key: "country", label: "Country", type: "text" },
          { key: "role", label: "Role", type: "text" },
          { key: "detail", label: "Detail", type: "textarea", wide: true },
          {
            key: "status",
            label: "Status",
            type: "select",
            options: [
              { value: "operating", label: "Operating" },
              { value: "expanding", label: "Expanding" },
            ],
          },
          { key: "image", label: "Photo", type: "image" },
        ],
      },
      {
        key: "socials",
        label: "Social links",
        type: "list",
        wide: true,
        itemTitleKey: "label",
        addLabel: "Add social link",
        of: [
          { key: "label", label: "Network", type: "text" },
          { key: "href", label: "Profile link", type: "url" },
          {
            key: "icon",
            label: "Icon",
            type: "icon",
            help: "Facebook, Twitter, Instagram, Youtube or Linkedin.",
          },
        ],
      },
    ],
    defaults: {
      name: company.name,
      shortName: company.shortName,
      tagline: company.tagline,
      description: company.description,
      email: company.email,
      emailAlt: company.emailAlt,
      phone: company.phone,
      phoneAlt: company.phoneAlt,
      address: company.address,
      mapLink: company.mapLink,
      mapEmbed:
        "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3025!2d69.2831565!3d34.5552596!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x38d16cb3eaa105d5%3A0xe4f019605915ab36!2sMaisam%20Steel%20Mill!5e0!3m2!1sen!2saf!4v1718900000000!5m2!1sen!2saf",
      founded: company.founded,
      ceo: company.ceo,
      stats: company.stats,
      offices: company.offices.map((office) => ({
        ...office,
        image: `/images/offices/${office.city.toLowerCase()}.jpg`,
      })),
      socials: company.socials,
    },
  },
  {
    key: "global.footer",
    label: "Footer",
    page: "global",
    description: "Footer buttons, column titles and the copyright line.",
    previewPath: "/",
    fields: [
      ...ctaFields("primaryCta", "Primary button"),
      ...ctaFields("secondaryCta", "Secondary button"),
      { key: "exploreTitle", label: "Links column title", type: "text" },
      { key: "newsletterTitle", label: "Newsletter column title", type: "text" },
      {
        key: "copyright",
        label: "Copyright line",
        type: "text",
        wide: true,
        help: "Use {year} for the current year and {company} for the company name.",
      },
    ],
    defaults: {
      primaryCtaLabel: "Get a quote",
      primaryCtaHref: "/contact",
      secondaryCtaLabel: "Learn more",
      secondaryCtaHref: "/about",
      exploreTitle: "Explore",
      newsletterTitle: "Stay tuned for more news",
      copyright: "© {year} {company}. All rights reserved.",
    },
  },
  {
    key: "global.seo",
    label: "SEO & sharing",
    page: "global",
    description: "Default page title, description and the image used when the site is shared.",
    previewPath: "/",
    fields: [
      { key: "metaTitle", label: "Default title", type: "text", wide: true },
      {
        key: "titleTemplate",
        label: "Title template",
        type: "text",
        wide: true,
        help: "Use %s where the page name should appear.",
      },
      { key: "metaDescription", label: "Meta description", type: "textarea", wide: true },
      { key: "ogImage", label: "Share image", type: "image" },
      {
        key: "keywords",
        label: "Keywords",
        type: "list",
        wide: true,
        itemTitleKey: "value",
        addLabel: "Add keyword",
        of: [{ key: "value", label: "Keyword", type: "text" }],
      },
    ],
    defaults: {
      metaTitle: "Maisam Steel Mill — Innovative metal solutions for industries",
      titleTemplate: "%s — Maisam Steel Mill",
      metaDescription:
        "Maisam Steel Mill — Afghanistan's first ISO-certified steel manufacturer. Rebar, angles and T-bars engineered to international standards since 2009.",
      ogImage: "/opengraph-image.png",
      keywords: [
        "Maisam Steel Mill",
        "MSM",
        "steel manufacturer Afghanistan",
        "ISO certified steel",
        "rebar",
        "steel angles",
        "T-bars",
        "structural steel",
        "Pol-e-Charkhi",
        "Kabul steel mill",
        "construction steel Afghanistan",
      ].map((value) => ({ value })),
    },
  },

  /* ──────────────────────────────── HOME ──────────────────────────────── */
  {
    key: "home.hero",
    label: "Hero",
    page: "home",
    description: "The full-screen opening band — background video, headline and the floating contact card.",
    previewPath: "/",
    fields: [
      {
        key: "backgroundVideo",
        label: "Background video",
        type: "video",
        help: "Plays muted on a loop. The poster image shows while it loads.",
      },
      { key: "posterImage", label: "Poster image", type: "image" },
      {
        key: "eyebrow",
        label: "Eyebrow",
        type: "text",
        help: "Use {short} for the short name and {founded} for the founding year.",
      },
      { key: "titleLead", label: "Headline", type: "text", wide: true },
      { key: "titleAccent", label: "Headline — accent word", type: "text" },
      { key: "body", label: "Intro paragraph", type: "textarea", wide: true },
      ...ctaFields("primaryCta", "Primary button"),
      ...ctaFields("secondaryCta", "Secondary button"),
      { key: "showStats", label: "Show the figures row", type: "boolean" },
      { key: "contactCardTitle", label: "Contact card title", type: "text" },
      { key: "contactCardAddress", label: "Contact card address", type: "text", wide: true },
    ],
    defaults: {
      backgroundVideo: "/videos/steel-hero.mp4",
      posterImage: "/images/hero.jpg",
      eyebrow: "{short} — Since {founded}",
      titleLead: "Innovative metal solutions for",
      titleAccent: "industries",
      body: `${company.description} We forge the certified steel that builds a nation — one beam, one bar, and one project at a time.`,
      primaryCtaLabel: "Get a quote",
      primaryCtaHref: "/contact",
      secondaryCtaLabel: "Learn more",
      secondaryCtaHref: "/about",
      showStats: true,
      contactCardTitle: "Get in touch",
      contactCardAddress: "Pol-e-Charkhi Industrial Park, Kabul",
    },
  },
  {
    key: "home.intro",
    label: "Intro — who we are",
    page: "home",
    description: "The photo collage and the opening story block.",
    previewPath: "/",
    fields: [
      ...headingFields,
      { key: "titleLead", label: "Heading", type: "text", wide: true },
      { key: "titleAccent", label: "Heading — accent words", type: "text" },
      {
        key: "paragraphs",
        label: "Paragraphs",
        type: "list",
        wide: true,
        itemTitleKey: "text",
        addLabel: "Add paragraph",
        of: [{ key: "text", label: "Paragraph", type: "textarea", wide: true }],
      },
      {
        key: "images",
        label: "Collage photos",
        type: "list",
        wide: true,
        itemTitleKey: "alt",
        addLabel: "Add photo",
        of: [
          { key: "src", label: "Photo", type: "image" },
          { key: "alt", label: "Alt text", type: "text" },
        ],
      },
      ...ctaFields("primaryCta", "Primary button"),
      ...ctaFields("secondaryCta", "Secondary button"),
    ],
    defaults: {
      eyebrowNumber: "01",
      eyebrowLabel: "",
      titleLead: "We're the future of the",
      titleAccent: "metallurgy industry",
      paragraphs: [
        {
          text: "Established in 2009, Maisam Steel Mill became the first steel manufacturer in Afghanistan to operate to international IEC/ISO standards. From our plant at Pol-e-Charkhi, we produce certified rebar, angles and T-bars for the projects rebuilding the country.",
        },
        {
          text: "Our purpose reaches beyond the mill floor — to build a domestic value chain, create skilled work, and set the regional benchmark for steel that lasts.",
        },
      ],
      images: [
        { src: "/images/intro-1.jpg", alt: "Steelworkers amid sparks on the mill floor" },
        { src: "/images/intro-2.jpg", alt: "Molten steel pouring in the furnace" },
        { src: "/images/intro-3.jpg", alt: "Hot-rolled steel bars on the line" },
        { src: "/images/intro-4.jpg", alt: "Finished steel sections" },
      ],
      primaryCtaLabel: "Our story",
      primaryCtaHref: "/about",
      secondaryCtaLabel: "Browse services",
      secondaryCtaHref: "/services",
    },
  },
  {
    key: "home.products",
    label: "Products showcase",
    page: "home",
    description: "Heading and link for the product grid. The products themselves live under Products.",
    previewPath: "/",
    fields: [
      ...headingFields,
      { key: "title", label: "Heading", type: "text", wide: true },
      { key: "description", label: "Description", type: "textarea", wide: true },
      ...ctaFields("link", "Browse link"),
      { key: "limit", label: "How many to show", type: "number" },
    ],
    defaults: {
      eyebrowNumber: "02",
      eyebrowLabel: "Products",
      title: "Steel built to specification",
      description:
        "Certified rebar, angles and T-bars today — with new structural products to ASTM A36 and EN 10025 standards on the way.",
      linkLabel: "Browse all products",
      linkHref: "/products",
      limit: 6,
    },
  },
  {
    key: "home.services",
    label: "Services grid",
    page: "home",
    description: "Heading, link and the background photo used on each service card.",
    previewPath: "/",
    fields: [
      ...headingFields,
      { key: "title", label: "Heading", type: "text", wide: true },
      ...ctaFields("link", "Browse link"),
      { key: "limit", label: "How many to show", type: "number" },
      {
        key: "cardImages",
        label: "Card photos",
        type: "list",
        wide: true,
        itemTitleKey: "src",
        addLabel: "Add photo",
        of: [{ key: "src", label: "Photo", type: "image" }],
      },
    ],
    defaults: {
      eyebrowNumber: "03",
      eyebrowLabel: "Services",
      title: "A comprehensive set of services",
      linkLabel: "Browse all services",
      linkHref: "/services",
      limit: 4,
      cardImages: [
        { src: "/images/service-1.jpg" },
        { src: "/images/service-2.jpg" },
        { src: "/images/service-3.jpg" },
        { src: "/images/service-4.jpg" },
      ],
    },
  },
  {
    key: "home.process",
    label: "Process timeline",
    page: "home",
    description: "The production lines, their stages, and every label around them.",
    previewPath: "/",
    fields: [
      ...headingFields,
      { key: "title", label: "Heading", type: "text", wide: true },
      { key: "lead", label: "Lead paragraph", type: "textarea", wide: true },
      {
        key: "processes",
        label: "Production lines",
        type: "list",
        wide: true,
        itemTitleKey: "label",
        addLabel: "Add production line",
        help: "Each line is one continuous run of the mill. Stages inside a line are shown in order.",
        of: [
          { key: "no", label: "Line number", type: "text" },
          { key: "label", label: "Line name", type: "text" },
          { key: "caption", label: "Caption", type: "text", help: "Short summary, e.g. \"Scrap to billet\"." },
          { key: "input", label: "Input", type: "text", help: "What this line starts from. Shown above the first stage." },
          {
            key: "steps",
            label: "Stages",
            type: "list",
            wide: true,
            itemTitleKey: "title",
            addLabel: "Add stage",
            of: [
              { key: "no", label: "Number", type: "text" },
              { key: "title", label: "Title", type: "text" },
              { key: "icon", label: "Icon", type: "icon" },
              { key: "output", label: "Output", type: "text", help: "What leaves this stage, e.g. \"Molten steel\"." },
              { key: "desc", label: "Description", type: "textarea", wide: true },
            ],
          },
        ],
      },
      { key: "closingText", label: "Closing line", type: "text", wide: true },
      // Every visible word in this section is editable — these are the small
      // fixed labels around the data (the readout, the chips), which would
      // otherwise be hardcoded in the component.
      { key: "stageLabel", label: "Label — \"Stage\"", type: "text" },
      { key: "stagesLabel", label: "Label — \"stages\"", type: "text" },
      { key: "lineLabel", label: "Label — \"Line\"", type: "text" },
      { key: "linesLabel", label: "Label — \"production lines\"", type: "text" },
      { key: "inputLabel", label: "Label — \"Input\"", type: "text" },
      { key: "outputLabel", label: "Label — \"Output\"", type: "text" },
      ...ctaFields("primaryCta", "Primary button"),
      ...ctaFields("secondaryCta", "Secondary button"),
    ],
    defaults: {
      eyebrowNumber: "04",
      eyebrowLabel: "Process",
      title: "Check how our process is done",
      lead: "One integrated mill controls every stage in-house — a melt shop that turns scrap into billet, and a rolling mill that turns billet into certified steel. Follow both lines, one stage at a time.",
      processes: [
        {
          no: "01",
          label: "Melt shop",
          caption: "Scrap to billet",
          input: "Raw material and recovered scrap",
          steps: [
            {
              no: "01",
              title: "Material selection",
              icon: "Recycle",
              output: "Graded charge",
              desc: "Raw material and recovered scrap are graded and weighed, then made up into a charge with the chemistry set for the heat that follows.",
            },
            {
              no: "02",
              title: "Melting",
              icon: "Flame",
              output: "Molten steel",
              desc: "The charge is melted in a controlled electric furnace. Temperature and composition are held to specification before the heat is tapped.",
            },
            {
              no: "03",
              title: "Casting",
              icon: "Droplets",
              output: "Billets",
              desc: "Molten steel is continuously cast into billets of a consistent section — the uniform, defect-free stock every finished length is rolled from.",
            },
            {
              no: "04",
              title: "Quality control",
              icon: "FlaskConical",
              output: "Verified billets",
              desc: "Every heat is sampled and checked for chemistry and soundness. Billets pass to the rolling mill only once the heat clears.",
            },
          ],
        },
        {
          no: "02",
          label: "Rolling mill",
          caption: "Billet to dispatch",
          input: "Verified billets from the melt shop",
          steps: [
            {
              no: "01",
              title: "Rolling",
              icon: "Cog",
              output: "Rebar, angles, T-bars",
              desc: "Reheated billets are hot-rolled into rebar, angles and T-bars at precise tolerances, then stamped MSM so every length stays traceable.",
            },
            {
              no: "02",
              title: "Shipping",
              icon: "Truck",
              output: "Bundled lengths",
              desc: "Rolled sections are cooled, cut to length and bundled by size and grade, then staged in the yard and loaded for transport.",
            },
            {
              no: "03",
              title: "Quality control",
              icon: "ShieldCheck",
              output: "Certified batch",
              desc: "Samples from every batch are lab-tested for yield, tensile strength and tolerance under ISO 9001 before the batch is cleared.",
            },
            {
              no: "04",
              title: "Dispatch",
              icon: "Package",
              output: "Delivered to site",
              desc: "Cleared batches leave the mill with their test certificate and MSM stamp, so what arrives on site can be traced back to the heat it came from.",
            },
          ],
        },
      ],
      closingText: "Ready to put our process to work?",
      stageLabel: "Stage",
      stagesLabel: "stages",
      lineLabel: "Line",
      linesLabel: "production lines",
      inputLabel: "Input",
      outputLabel: "Output",
      primaryCtaLabel: "Get a quote",
      primaryCtaHref: "/contact",
      secondaryCtaLabel: "All services",
      secondaryCtaHref: "/services",
    },
  },
  {
    key: "home.quality",
    label: "Quality & certificates",
    page: "home",
    description: "The ISO statement, the two figures, the commitment list and the certificate gallery.",
    previewPath: "/",
    fields: [
      ...headingFields,
      { key: "title", label: "Heading", type: "text", wide: true },
      { key: "body", label: "Body", type: "textarea", wide: true },
      { key: "statOneValue", label: "Figure 1 — value", type: "number" },
      { key: "statOneSuffix", label: "Figure 1 — suffix", type: "text" },
      { key: "statOneLabel", label: "Figure 1 — label", type: "text" },
      { key: "statTwoValue", label: "Figure 2 — value", type: "number" },
      { key: "statTwoSuffix", label: "Figure 2 — suffix", type: "text" },
      { key: "statTwoLabel", label: "Figure 2 — label", type: "text" },
      {
        key: "commitments",
        label: "Commitments",
        type: "list",
        wide: true,
        itemTitleKey: "text",
        addLabel: "Add commitment",
        of: [{ key: "text", label: "Commitment", type: "text" }],
      },
      { key: "note", label: "Note under the list", type: "text", wide: true },
      {
        key: "certificates",
        label: "Certificates",
        type: "list",
        wide: true,
        itemTitleKey: "title",
        addLabel: "Add certificate",
        of: [
          { key: "title", label: "Title", type: "text" },
          { key: "src", label: "Certificate image", type: "image" },
        ],
      },
    ],
    defaults: {
      eyebrowNumber: "05",
      eyebrowLabel: "Quality",
      title: "Exceptional quality that can't be beaten",
      body: "Under our ISO 9001 quality system, every batch is tested for tensile strength, dimensional tolerance and surface quality. These aren't certificates on a wall — they are a promise in the steel, accredited and verifiable.",
      statOneValue: 100,
      statOneSuffix: "%",
      statOneLabel: "Every batch lab-tested",
      statTwoValue: 4,
      statTwoSuffix: "",
      statTwoLabel: "International ISO standards",
      commitments: [
        { text: "Tensile, dimensional & surface checks" },
        { text: "Per-batch test certificates" },
        { text: "MSM-stamped traceability on every length" },
      ],
      note: "Click any certificate to view it in full.",
      certificates: bundledCertificates,
    },
  },
  {
    key: "home.lab",
    label: "Testing laboratory",
    page: "home",
    description: "The in-house lab panels and the list of standards.",
    previewPath: "/",
    fields: [
      ...headingFields,
      { key: "eyebrow", label: "Eyebrow text", type: "text" },
      { key: "title", label: "Heading", type: "text", wide: true },
      { key: "lead", label: "Lead paragraph", type: "textarea", wide: true },
      {
        key: "tests",
        label: "Tests",
        type: "list",
        wide: true,
        itemTitleKey: "title",
        addLabel: "Add test",
        of: [
          { key: "title", label: "Title", type: "text" },
          { key: "icon", label: "Icon", type: "icon" },
          { key: "image", label: "Photo", type: "image" },
          { key: "desc", label: "Description", type: "textarea", wide: true },
        ],
      },
      {
        key: "standards",
        label: "Standards",
        type: "list",
        wide: true,
        itemTitleKey: "value",
        addLabel: "Add standard",
        of: [{ key: "value", label: "Standard", type: "text" }],
      },
    ],
    defaults: {
      eyebrowNumber: "06",
      eyebrowLabel: "",
      eyebrow: lab.eyebrow,
      title: lab.title,
      lead: lab.lead,
      tests: lab.tests,
      standards: lab.standards.map((value) => ({ value })),
    },
  },
  {
    key: "home.presence",
    label: "Global presence & trading",
    page: "home",
    description:
      "The office cards and the international-trading panel. Offices themselves are edited under Global → Company details.",
    previewPath: "/",
    fields: [
      ...headingFields,
      { key: "titleLead", label: "Heading", type: "text", wide: true },
      { key: "titleAccent", label: "Heading — accent word", type: "text" },
      { key: "description", label: "Description", type: "textarea", wide: true },
      { key: "tradingEyebrow", label: "Trading — eyebrow", type: "text" },
      { key: "tradingTitle", label: "Trading — heading", type: "text", wide: true },
      { key: "tradingLead", label: "Trading — lead", type: "textarea", wide: true },
      {
        key: "tradingPoints",
        label: "Trading — points",
        type: "list",
        wide: true,
        itemTitleKey: "text",
        addLabel: "Add point",
        of: [{ key: "text", label: "Point", type: "textarea", wide: true }],
      },
    ],
    defaults: {
      eyebrowNumber: "07",
      eyebrowLabel: "Where we operate",
      titleLead: "A growing footprint across the",
      titleAccent: "region",
      description:
        "From our mill in Kabul to trading offices reaching the Gulf and Türkiye — connecting Afghan industry to international supply.",
      tradingEyebrow: trading.eyebrow,
      tradingTitle: trading.title,
      tradingLead: trading.lead,
      tradingPoints: trading.points.map((text) => ({ text })),
    },
  },
  {
    key: "home.projects",
    label: "Projects showcase",
    page: "home",
    description: "Heading and link for the projects band. The projects themselves live under Projects.",
    previewPath: "/",
    fields: [
      ...headingFields,
      { key: "title", label: "Heading", type: "text", wide: true },
      { key: "limit", label: "How many to show", type: "number" },
      ...ctaFields("link", "All-projects link"),
    ],
    defaults: {
      eyebrowNumber: "08",
      eyebrowLabel: "Major projects",
      title: "Built into the nation's biggest works",
      limit: 2,
      linkLabel: "All projects",
      linkHref: "/projects",
    },
  },
  {
    key: "home.events",
    label: "Events teaser",
    page: "home",
    description: "The band of latest events on the homepage. Events themselves are managed under Events.",
    previewPath: "/",
    fields: [
      { key: "enabled", label: "Show this section", type: "boolean" },
      ...headingFields,
      { key: "title", label: "Heading", type: "text", wide: true },
      { key: "description", label: "Description", type: "textarea", wide: true },
      { key: "limit", label: "How many to show", type: "number" },
      ...ctaFields("link", "All-events link"),
    ],
    defaults: {
      enabled: true,
      eyebrowNumber: "09",
      eyebrowLabel: "Events",
      title: "What's happening at the mill",
      description: "Exhibitions, site visits, milestones and announcements from Maisam Steel Mill.",
      limit: 3,
      linkLabel: "All events",
      linkHref: "/events",
    },
  },
  {
    key: "home.newsletter",
    label: "Newsletter banner",
    page: "home",
    description: "The orange newsletter sign-up band.",
    previewPath: "/",
    fields: [
      { key: "eyebrow", label: "Eyebrow", type: "text" },
      { key: "title", label: "Heading", type: "text", wide: true },
      { key: "body", label: "Body", type: "textarea", wide: true },
      {
        key: "perks",
        label: "Perks",
        type: "list",
        wide: true,
        itemTitleKey: "text",
        addLabel: "Add perk",
        of: [{ key: "text", label: "Perk", type: "text" }],
      },
      { key: "placeholder", label: "Input placeholder", type: "text" },
      { key: "buttonLabel", label: "Button label", type: "text" },
      { key: "successMessage", label: "Success message", type: "text", wide: true },
    ],
    defaults: {
      eyebrow: "Newsletter",
      title: "Stay ahead of the mill floor",
      body: "Production updates, technical guides and industry news — delivered straight to your inbox.",
      perks: [{ text: "Monthly digest" }, { text: "No spam, ever" }, { text: "Unsubscribe anytime" }],
      placeholder: "Enter your email",
      buttonLabel: "Subscribe",
      successMessage: "Thanks for joining — please check your inbox to confirm.",
    },
  },
  {
    key: "home.testimonials",
    label: "Testimonials",
    page: "home",
    description: "Client quotes shown on the dark band.",
    previewPath: "/",
    fields: [
      ...headingFields,
      { key: "title", label: "Heading", type: "text", wide: true },
      {
        key: "items",
        label: "Quotes",
        type: "list",
        wide: true,
        itemTitleKey: "name",
        addLabel: "Add testimonial",
        of: [
          { key: "quote", label: "Quote", type: "textarea", wide: true },
          { key: "name", label: "Name", type: "text" },
          { key: "location", label: "Role / location", type: "text" },
          { key: "image", label: "Portrait", type: "image" },
        ],
      },
    ],
    defaults: {
      eyebrowNumber: "10",
      eyebrowLabel: "Testimonials",
      title: "What our clients say about our work",
      items: testimonials,
    },
  },
  {
    key: "home.logos",
    label: "Partners strip",
    page: "home",
    description: "The scrolling partner marquee.",
    previewPath: "/",
    fields: [
      ...headingFields,
      { key: "title", label: "Heading", type: "text", wide: true },
      {
        key: "partners",
        label: "Partners",
        type: "list",
        wide: true,
        itemTitleKey: "name",
        addLabel: "Add partner",
        of: [
          { key: "name", label: "Name", type: "text" },
          {
            key: "logo",
            label: "Logo (optional)",
            type: "image",
            help: "Leave empty to show the name as text.",
          },
        ],
      },
    ],
    defaults: {
      eyebrowNumber: "11",
      eyebrowLabel: "Partners",
      title: "Brands & companies we worked with",
      partners: [
        {
          name: "Khwajazada Sistan Construction and Construction Materials Production Co",
          logo: "",
        },
        { name: "Khwaja Zada & Sons Ltd", logo: "" },
        { name: "Caravell", logo: "/images/partners/caravell.png" },
        { name: "Payman Group", logo: "/images/partners/payman-group.png" },
        { name: "Payman Ice Cream", logo: "/images/partners/payman-ice-cream.png" },
        { name: "Payman Battery", logo: "/images/partners/payman-battery.png" },
        { name: "Chiita", logo: "/images/partners/chiita.png" },
      ],
    },
  },
  {
    key: "home.catalog",
    label: "Catalog & downloads",
    page: "home",
    description: "Downloadable company profile and brochures.",
    previewPath: "/",
    fields: [
      { key: "eyebrow", label: "Eyebrow", type: "text" },
      { key: "titleLead", label: "Heading", type: "text", wide: true },
      { key: "titleAccent", label: "Heading — accent words", type: "text" },
      { key: "body", label: "Body", type: "textarea", wide: true },
      {
        key: "files",
        label: "Files",
        type: "list",
        wide: true,
        itemTitleKey: "label",
        addLabel: "Add file",
        of: [
          { key: "label", label: "Title", type: "text" },
          { key: "desc", label: "Description", type: "textarea", wide: true },
          {
            key: "href",
            label: "File link",
            type: "file",
            help: "Upload a PDF, or paste a path such as /downloads/profile.pdf.",
          },
          { key: "size", label: "Size label", type: "text", placeholder: "PDF · 2.5 MB" },
        ],
      },
    ],
    defaults: {
      eyebrow: "Catalog & downloads",
      titleLead: "Take the full specs",
      titleAccent: "with you",
      body: "Download our company profile and product brochure — everything your procurement and engineering teams need to specify Maisam steel.",
      files: [
        {
          label: "Company Profile",
          desc: "Full 2025 profile — overview, products, certifications.",
          href: "/downloads/msm-company-profile.pdf",
          size: "PDF · 2.5 MB",
        },
        {
          label: "Product Brochure",
          desc: "Bilingual trifold — rebar, angles and T-bar specs.",
          href: "/downloads/msm-brochure.pdf",
          size: "PDF · 1.2 MB",
        },
      ],
    },
  },
  {
    key: "home.blog",
    label: "Blog teaser",
    page: "home",
    description: "The latest-articles band. Articles themselves live under Blog.",
    previewPath: "/",
    fields: [
      ...headingFields,
      { key: "title", label: "Heading", type: "text", wide: true },
      { key: "description", label: "Description", type: "textarea", wide: true },
      { key: "limit", label: "How many to show", type: "number" },
      ...ctaFields("link", "Browse link"),
    ],
    defaults: {
      eyebrowNumber: "12",
      eyebrowLabel: "Blog",
      title: "News & articles",
      description: "Guides, resources and updates from the mill floor.",
      limit: 3,
      linkLabel: "Browse all articles",
      linkHref: "/blog",
    },
  },

  /* ──────────────────────────────── ABOUT ─────────────────────────────── */
  {
    key: "about.hero",
    label: "Page header",
    page: "about",
    description: "The dark banner at the top of the About page.",
    previewPath: "/about",
    fields: [
      { key: "eyebrow", label: "Eyebrow", type: "text" },
      { key: "titleLead", label: "Heading", type: "text", wide: true },
      { key: "titleAccent", label: "Heading — accent words", type: "text" },
      { key: "lead", label: "Lead paragraph", type: "textarea", wide: true },
    ],
    defaults: {
      eyebrow: "About us",
      titleLead: "Building a nation on",
      titleAccent: "certified steel",
      lead: "Established in 2009, Maisam Steel Mill is Afghanistan's first ISO-certified steel manufacturer — forging the materials that rebuild the country.",
    },
  },
  {
    key: "about.story",
    label: "Our story",
    page: "about",
    description: "The photo and story block below the header.",
    previewPath: "/about",
    fields: [
      ...headingFields,
      { key: "title", label: "Heading", type: "text", wide: true },
      { key: "image", label: "Photo", type: "image" },
      { key: "video", label: "Video (optional)", type: "video", help: "When set, a video plays here instead of the photo." },
      {
        key: "paragraphs",
        label: "Paragraphs",
        type: "list",
        wide: true,
        itemTitleKey: "text",
        addLabel: "Add paragraph",
        of: [{ key: "text", label: "Paragraph", type: "textarea", wide: true }],
      },
      ...ctaFields("primaryCta", "Button"),
    ],
    defaults: {
      eyebrowNumber: "01",
      eyebrowLabel: "Our story",
      title: "From a bold dream to the nation's mill",
      image: "/images/about.jpg",
      video: "",
      paragraphs: [
        {
          text: "What began in 2009 with a simple belief — that Afghanistan deserves nothing less than the highest-quality materials for its infrastructure — has grown into the country's most trusted steel manufacturer.",
        },
        {
          text: "Through international partnerships and ISO certification, we have introduced standardized, high-quality steel to the domestic market and employed hundreds of talented Afghans along the way.",
        },
      ],
      primaryCtaLabel: "Work with us",
      primaryCtaHref: "/contact",
    },
  },
  {
    key: "about.values",
    label: "Values",
    page: "about",
    description: "The four value cards.",
    previewPath: "/about",
    fields: [
      ...headingFields,
      { key: "title", label: "Heading", type: "text", wide: true },
      {
        key: "items",
        label: "Values",
        type: "list",
        wide: true,
        itemTitleKey: "title",
        addLabel: "Add value",
        of: [
          { key: "icon", label: "Icon", type: "icon" },
          { key: "title", label: "Title", type: "text" },
          { key: "desc", label: "Description", type: "textarea", wide: true },
        ],
      },
    ],
    defaults: {
      eyebrowNumber: "02",
      eyebrowLabel: "What sets us apart",
      title: "Why Afghanistan builds with Maisam",
      items: [
        {
          icon: "ShieldCheck",
          title: "First & only ISO-certified",
          desc: "The pioneer mill operating to international quality, safety and environmental standards.",
        },
        {
          icon: "Cog",
          title: "Reliable high capacity",
          desc: "336+ metric tons of certified steel every day — supply you can plan around.",
        },
        {
          icon: "MapPin",
          title: "Nationwide reach",
          desc: "Trusted and available across nearly every province of Afghanistan.",
        },
        {
          icon: "Recycle",
          title: "Built for Afghanistan",
          desc: "Creating jobs, transferring skills and building a domestic value chain.",
        },
      ],
    },
  },
  {
    key: "about.ceo",
    label: "CEO message",
    page: "about",
    description: "Portrait, greeting and the letter from the CEO.",
    previewPath: "/about",
    fields: [
      { key: "name", label: "Name", type: "text" },
      { key: "role", label: "Role", type: "text" },
      { key: "image", label: "Portrait", type: "image" },
      { key: "greeting", label: "Greeting", type: "text", wide: true },
      {
        key: "paragraphs",
        label: "Letter",
        type: "list",
        wide: true,
        itemTitleKey: "text",
        addLabel: "Add paragraph",
        of: [{ key: "text", label: "Paragraph", type: "textarea", wide: true }],
      },
    ],
    defaults: {
      name: ceoMessage.name,
      role: ceoMessage.role,
      image: ceoMessage.image,
      greeting: ceoMessage.greeting,
      paragraphs: ceoMessage.paragraphs.map((text) => ({ text })),
    },
  },
  {
    key: "about.visionMission",
    label: "Vision & mission",
    page: "about",
    description: "The two statement panels.",
    previewPath: "/about",
    fields: [
      { key: "visionTitle", label: "Vision — title", type: "text" },
      { key: "visionBody", label: "Vision — body", type: "textarea", wide: true },
      { key: "missionTitle", label: "Mission — title", type: "text" },
      { key: "missionBody", label: "Mission — body", type: "textarea", wide: true },
      { key: "image", label: "Supporting photo", type: "image" },
    ],
    defaults: {
      visionTitle: vision.title,
      visionBody: vision.body,
      missionTitle: mission.title,
      missionBody: mission.body,
      image: "",
    },
  },
  {
    key: "about.mining",
    label: "Mining & research",
    page: "about",
    description: "The mine-to-mill research programme block.",
    previewPath: "/about",
    fields: [
      { key: "eyebrow", label: "Eyebrow", type: "text" },
      { key: "title", label: "Heading", type: "text", wide: true },
      { key: "lead", label: "Lead paragraph", type: "textarea", wide: true },
      { key: "image", label: "Photo", type: "image" },
      {
        key: "points",
        label: "Points",
        type: "list",
        wide: true,
        itemTitleKey: "title",
        addLabel: "Add point",
        of: [
          { key: "icon", label: "Icon", type: "icon" },
          { key: "title", label: "Title", type: "text" },
          { key: "desc", label: "Description", type: "textarea", wide: true },
        ],
      },
    ],
    defaults: {
      eyebrow: mining.eyebrow,
      title: mining.title,
      lead: mining.lead,
      image: "",
      points: mining.points,
    },
  },
  {
    key: "about.team",
    label: "Leadership team",
    page: "about",
    description: "The people behind the steel.",
    previewPath: "/about",
    fields: [
      ...headingFields,
      { key: "title", label: "Heading", type: "text", wide: true },
      { key: "description", label: "Description", type: "textarea", wide: true },
      {
        key: "members",
        label: "Team members",
        type: "list",
        wide: true,
        itemTitleKey: "name",
        addLabel: "Add member",
        of: [
          { key: "slug", label: "Slug", type: "text", help: "Used in the URL, e.g. jane-doe." },
          { key: "name", label: "Name", type: "text" },
          { key: "role", label: "Role", type: "text" },
          { key: "image", label: "Portrait", type: "image" },
          { key: "bio", label: "Biography", type: "textarea", wide: true },
        ],
      },
    ],
    defaults: {
      eyebrowNumber: "03",
      eyebrowLabel: "Our team",
      title: "The people behind the steel",
      description: "Leadership, engineering and quality — the team keeping certified steel flowing.",
      members: team,
    },
  },
  {
    key: "about.partner",
    label: "Become a partner",
    page: "about",
    description: "The partnership call-to-action block.",
    previewPath: "/about",
    fields: [
      { key: "eyebrow", label: "Eyebrow", type: "text" },
      { key: "title", label: "Heading", type: "text", wide: true },
      { key: "lead", label: "Lead paragraph", type: "textarea", wide: true },
      {
        key: "options",
        label: "Partner types",
        type: "list",
        wide: true,
        itemTitleKey: "title",
        addLabel: "Add partner type",
        of: [
          { key: "icon", label: "Icon", type: "icon" },
          { key: "title", label: "Title", type: "text" },
          { key: "desc", label: "Description", type: "textarea", wide: true },
        ],
      },
      ...ctaFields("primaryCta", "Button"),
    ],
    defaults: {
      eyebrow: partner.eyebrow,
      title: partner.title,
      lead: partner.lead,
      options: partner.options,
      primaryCtaLabel: "Talk to us",
      primaryCtaHref: "/contact",
    },
  },

  /* ─────────────────────────────── PRODUCTS ───────────────────────────── */
  {
    key: "products.hero",
    label: "Page header",
    page: "products",
    description: "The dark banner at the top of the Products page.",
    previewPath: "/products",
    fields: [
      { key: "eyebrow", label: "Eyebrow", type: "text" },
      { key: "titleLead", label: "Heading", type: "text", wide: true },
      { key: "titleAccent", label: "Heading — accent words", type: "text" },
      { key: "lead", label: "Lead paragraph", type: "textarea", wide: true },
    ],
    defaults: {
      eyebrow: "Products",
      titleLead: "Steel built to",
      titleAccent: "specification",
      lead: "A complete structural portfolio — each grade rolled to international standard and stamped MSM.",
    },
  },
  {
    key: "products.catalog",
    label: "Product catalogue",
    page: "products",
    description: "Every product on the site — name, photo, price, specification and description.",
    previewPath: "/products",
    fields: [
      {
        key: "categories",
        label: "Filter categories",
        type: "list",
        wide: true,
        itemTitleKey: "value",
        addLabel: "Add category",
        of: [{ key: "value", label: "Category", type: "text" }],
      },
      {
        key: "items",
        label: "Products",
        type: "list",
        wide: true,
        itemTitleKey: "name",
        addLabel: "Add product",
        of: [
          { key: "slug", label: "Slug", type: "text", help: "Used in the URL, e.g. steel-rebar." },
          { key: "name", label: "Name", type: "text" },
          { key: "category", label: "Category", type: "text" },
          { key: "price", label: "Price (USD / MT)", type: "number" },
          { key: "image", label: "Photo", type: "image" },
          { key: "video", label: "Video (optional)", type: "video" },
          { key: "comingSoon", label: "Coming soon", type: "boolean" },
          { key: "description", label: "Description", type: "textarea", wide: true },
          {
            key: "specs",
            label: "Specification",
            type: "list",
            wide: true,
            itemTitleKey: "key",
            addLabel: "Add specification row",
            of: [
              { key: "key", label: "Label", type: "text" },
              { key: "value", label: "Value", type: "text" },
            ],
          },
        ],
      },
    ],
    defaults: {
      categories: productCategories.map((value) => ({ value })),
      items: products.map((product) => ({ ...product, video: "" })),
    },
  },

  /* ─────────────────────────────── SERVICES ───────────────────────────── */
  {
    key: "services.hero",
    label: "Page header",
    page: "services",
    description: "The dark banner at the top of the Services page.",
    previewPath: "/services",
    fields: [
      { key: "eyebrow", label: "Eyebrow", type: "text" },
      { key: "titleLead", label: "Heading", type: "text", wide: true },
      { key: "titleAccent", label: "Heading — accent word", type: "text" },
      { key: "lead", label: "Lead paragraph", type: "textarea", wide: true },
    ],
    defaults: {
      eyebrow: "Services",
      titleLead: "A comprehensive set of",
      titleAccent: "services",
      lead: "From melt to market, every stage of steel production handled in-house and to international standard.",
    },
  },
  {
    key: "services.catalog",
    label: "Service list",
    page: "services",
    description: "Every service — title, icon, summary, full description and capabilities.",
    previewPath: "/services",
    fields: [
      {
        key: "items",
        label: "Services",
        type: "list",
        wide: true,
        itemTitleKey: "title",
        addLabel: "Add service",
        of: [
          { key: "slug", label: "Slug", type: "text", help: "Used in the URL, e.g. heat-treatment." },
          { key: "title", label: "Title", type: "text" },
          { key: "icon", label: "Icon", type: "icon" },
          { key: "image", label: "Photo", type: "image" },
          { key: "video", label: "Video (optional)", type: "video" },
          { key: "shortDescription", label: "Short description", type: "textarea", wide: true },
          { key: "fullDescription", label: "Full description", type: "textarea", wide: true },
          {
            key: "capabilities",
            label: "Capabilities",
            type: "list",
            wide: true,
            itemTitleKey: "value",
            addLabel: "Add capability",
            of: [{ key: "value", label: "Capability", type: "text" }],
          },
        ],
      },
    ],
    defaults: {
      items: services.map((service, index) => ({
        ...service,
        image: `/images/service-${index + 1}.jpg`,
        video: "",
        capabilities: service.capabilities.map((value) => ({ value })),
      })),
    },
  },

  /* ─────────────────────────────── PROJECTS ───────────────────────────── */
  {
    key: "projects.hero",
    label: "Page header",
    page: "projects",
    description: "The dark banner at the top of the Projects page.",
    previewPath: "/projects",
    fields: [
      { key: "eyebrow", label: "Eyebrow", type: "text" },
      { key: "titleLead", label: "Heading", type: "text", wide: true },
      { key: "titleAccent", label: "Heading — accent words", type: "text" },
      { key: "lead", label: "Lead paragraph", type: "textarea", wide: true },
    ],
    defaults: {
      eyebrow: "Our work",
      titleLead: "Major",
      titleAccent: "completed projects",
      lead: "From international partnerships to nationwide supply, Maisam steel is built into the projects rebuilding Afghanistan.",
    },
  },
  {
    key: "projects.list",
    label: "Project list",
    page: "projects",
    description: "Every project — title, partner, year, photo or video and description.",
    previewPath: "/projects",
    fields: [
      {
        key: "items",
        label: "Projects",
        type: "list",
        wide: true,
        itemTitleKey: "title",
        addLabel: "Add project",
        of: [
          { key: "title", label: "Title", type: "text" },
          { key: "partner", label: "Partner", type: "text" },
          { key: "year", label: "Year", type: "text" },
          { key: "location", label: "Location", type: "text" },
          { key: "category", label: "Category", type: "text" },
          { key: "image", label: "Photo", type: "image" },
          { key: "video", label: "Video (optional)", type: "video" },
          { key: "description", label: "Description", type: "textarea", wide: true },
        ],
      },
    ],
    defaults: { items: projects.map((project) => ({ ...project, video: "" })) },
  },

  /* ──────────────────────────────── EVENTS ────────────────────────────── */
  {
    key: "events.hero",
    label: "Page header",
    page: "events",
    description: "The dark banner at the top of the Events page.",
    previewPath: "/events",
    fields: [
      { key: "eyebrow", label: "Eyebrow", type: "text" },
      { key: "titleLead", label: "Heading", type: "text", wide: true },
      { key: "titleAccent", label: "Heading — accent word", type: "text" },
      { key: "lead", label: "Lead paragraph", type: "textarea", wide: true },
      { key: "emptyState", label: "Empty-state message", type: "text", wide: true },
    ],
    defaults: {
      eyebrow: "Events",
      titleLead: "News, milestones and",
      titleAccent: "events",
      lead: "Exhibitions, site visits, partnerships and announcements from Maisam Steel Mill.",
      emptyState: "No events published yet — check back soon.",
    },
  },

  /* ───────────────────────────────── BLOG ─────────────────────────────── */
  {
    key: "blog.hero",
    label: "Page header",
    page: "blog",
    description: "The dark banner at the top of the Blog page.",
    previewPath: "/blog",
    fields: [
      { key: "eyebrow", label: "Eyebrow", type: "text" },
      { key: "titleLead", label: "Heading", type: "text", wide: true },
      { key: "titleAccent", label: "Heading — accent word", type: "text" },
      { key: "lead", label: "Lead paragraph", type: "textarea", wide: true },
    ],
    defaults: {
      eyebrow: "Blog",
      titleLead: "News &",
      titleAccent: "articles",
      lead: "Guides, resources and updates from the mill floor.",
    },
  },
  {
    key: "blog.posts",
    label: "Articles",
    page: "blog",
    description: "Every article — title, cover image, excerpt and body.",
    previewPath: "/blog",
    fields: [
      {
        key: "categories",
        label: "Categories",
        type: "list",
        wide: true,
        itemTitleKey: "value",
        addLabel: "Add category",
        of: [{ key: "value", label: "Category", type: "text" }],
      },
      {
        key: "items",
        label: "Articles",
        type: "list",
        wide: true,
        itemTitleKey: "title",
        addLabel: "Add article",
        of: [
          { key: "slug", label: "Slug", type: "text", help: "Used in the URL." },
          { key: "title", label: "Title", type: "text" },
          { key: "category", label: "Category", type: "text" },
          { key: "date", label: "Date", type: "text", placeholder: "2026-05-12" },
          { key: "author", label: "Author", type: "text" },
          { key: "image", label: "Cover image", type: "image" },
          { key: "video", label: "Video (optional)", type: "video" },
          { key: "excerpt", label: "Excerpt", type: "textarea", wide: true },
          { key: "body", label: "Body", type: "markdown", wide: true },
        ],
      },
    ],
    defaults: {
      categories: postCategories.map((value) => ({ value })),
      items: posts.map((post) => ({ ...post, video: "" })),
    },
  },

  /* ─────────────────────────────── CONTACT ────────────────────────────── */
  {
    key: "contact.hero",
    label: "Page header",
    page: "contact",
    description: "The dark banner at the top of the Contact page.",
    previewPath: "/contact",
    fields: [
      { key: "eyebrow", label: "Eyebrow", type: "text" },
      { key: "titleLead", label: "Heading", type: "text", wide: true },
      { key: "titleAccent", label: "Heading — accent words", type: "text" },
      { key: "lead", label: "Lead paragraph", type: "textarea", wide: true },
    ],
    defaults: {
      eyebrow: "Contact",
      titleLead: "Let's build",
      titleAccent: "something that lasts",
      lead: "Tell us your sizes, quantities and delivery province — we respond with a quote and lead time, usually within 24 hours.",
    },
  },
  {
    key: "contact.form",
    label: "Form & details",
    page: "contact",
    description: "Headings, button label and the confirmation message on the contact form.",
    previewPath: "/contact",
    fields: [
      { key: "formTitle", label: "Form heading", type: "text", wide: true },
      { key: "detailsTitle", label: "Details heading", type: "text", wide: true },
      { key: "submitLabel", label: "Submit button label", type: "text" },
      { key: "successMessage", label: "Success message", type: "text", wide: true },
      { key: "showMap", label: "Show the map", type: "boolean" },
      { key: "mapLinkLabel", label: "Map link label", type: "text", wide: true },
    ],
    defaults: {
      formTitle: "Send us a message",
      detailsTitle: "Contact details",
      submitLabel: "Send message",
      successMessage: "Thanks — we've received your message and will reply shortly.",
      showMap: true,
      mapLinkLabel: "Open in Google Maps →",
    },
  },
];

export const sectionsByKey = new Map(sectionDefs.map((section) => [section.key, section]));

export function getSectionDef(key: string) {
  return sectionsByKey.get(key) ?? null;
}

export function sectionsForPage(page: string) {
  return sectionDefs.filter((section) => section.page === page);
}

export function isSectionKey(key: string): boolean {
  return sectionsByKey.has(key);
}
